 # How to code a Dataset class

In [3]:
import os

file = os.listdir('/Users/asim/Downloads/Label_Practise/CamVid/train')
print(file)

['0016E5_08490.png', '0001TP_009540.png', '0016E5_02340.png', '0016E5_08137.png', '0016E5_08123.png', '0001TP_009420.png', '0006R0_f02430.png', '0006R0_f03060.png', '0016E5_06720.png', '0016E5_08043.png', '0016E5_08057.png', 'Seq05VD_f03660.png', '0006R0_f03510.png', '0001TP_009810.png', '0016E5_04650.png', '0001TP_009390.png', 'Seq05VD_f01260.png', '0016E5_08095.png', '0016E5_08081.png', '0006R0_f01110.png', '0016E5_06090.png', 'Seq05VD_f00630.png', '0006R0_f03840.png', '0016E5_01890.png', 'Seq05VD_f02190.png', 'Seq05VD_f00750.png', '0016E5_05610.png', '0001TP_009780.png', '0006R0_f01500.png', '0016E5_06480.png', 'Seq05VD_f04050.png', '0016E5_07993.png', 'Seq05VD_f03930.png', '0016E5_05160.png', '0016E5_00540.png', '0016E5_08097.png', '0016E5_08083.png', '0016E5_01500.png', 'Seq05VD_f01920.png', '0016E5_08041.png', '0016E5_08055.png', '0016E5_04860.png', '0006R0_f02340.png', '0016E5_00390.png', '0016E5_07560.png', 'Seq05VD_f00960.png', '0016E5_08135.png', '0016E5_08121.png', 'Seq05VD_

In [ ]:
# Now as it is not in order to make it in order we have to use 'sorted'

file = sorted(os.listdir('/Users/asim/Downloads/Label_Practise/CamVid/train'))

print(file)

['0001TP_009210.png', '0001TP_009240.png', '0001TP_009390.png', '0001TP_009420.png', '0001TP_009450.png', '0001TP_009480.png', '0001TP_009510.png', '0001TP_009540.png', '0001TP_009690.png', '0001TP_009720.png', '0001TP_009750.png', '0001TP_009780.png', '0001TP_009810.png', '0001TP_009840.png', '0001TP_009990.png', '0001TP_010020.png', '0001TP_010050.png', '0001TP_010080.png', '0001TP_010110.png', '0001TP_010140.png', '0001TP_010290.png', '0001TP_010320.png', '0001TP_010350.png', '0001TP_010380.png', '0006R0_f00930.png', '0006R0_f00960.png', '0006R0_f01110.png', '0006R0_f01140.png', '0006R0_f01170.png', '0006R0_f01200.png', '0006R0_f01230.png', '0006R0_f01260.png', '0006R0_f01410.png', '0006R0_f01440.png', '0006R0_f01470.png', '0006R0_f01500.png', '0006R0_f01530.png', '0006R0_f01560.png', '0006R0_f01710.png', '0006R0_f01740.png', '0006R0_f01770.png', '0006R0_f01800.png', '0006R0_f01830.png', '0006R0_f01860.png', '0006R0_f02010.png', '0006R0_f02040.png', '0006R0_f02070.png', '0006R0_f021

In [5]:
# Now as some files have text or .ds_store(for mac) to remove this we use Filter i.e.:

file = sorted([
    f for f in os.listdir('/Users/asim/Downloads/Label_Practise/CamVid/train')
    if f.endswith(('.png', '.jpg'))
])

In [8]:
# Now we want the full path so lets do this

paths = sorted([
    os.path.join('/Users/asim/Downloads/Label_Practise/CamVid/train', f)
    for f in os.listdir('/Users/asim/Downloads/Label_Practise/CamVid/train')
    if f.endswith(('.png','.jpg'))
])

print(paths)

['/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009210.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009240.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009390.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009420.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009450.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009480.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009510.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009540.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009690.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009720.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009750.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009780.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009810.png', '/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009840.png', '/Use

Open Python in your notebook. Run that block. Then run a variation: list only files that contain the substring '_00' in their name. Try it. Tell me the line you wrote.

In [9]:
files_c = sorted([
    f for f in os.listdir('/Users/asim/Downloads/Label_Practise/CamVid/train')
    if '_00' in f
])

print(files_c)

['0001TP_009210.png', '0001TP_009240.png', '0001TP_009390.png', '0001TP_009420.png', '0001TP_009450.png', '0001TP_009480.png', '0001TP_009510.png', '0001TP_009540.png', '0001TP_009690.png', '0001TP_009720.png', '0001TP_009750.png', '0001TP_009780.png', '0001TP_009810.png', '0001TP_009840.png', '0001TP_009990.png', '0016E5_00390.png', '0016E5_00540.png', '0016E5_00570.png', '0016E5_00600.png', '0016E5_00630.png', '0016E5_00660.png', '0016E5_00690.png', '0016E5_00840.png', '0016E5_00870.png', '0016E5_00901.png', '0016E5_00930.png', '0016E5_00960.png', '0016E5_00990.png']


## Pattern 2

Openning an image file

In [2]:
import cv2

img = cv2.imread('/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009210.png')
print(img.shape)    # (256, 256, 3)
print(img.dtype)    # uint8

(720, 960, 3)
uint8


cv2 always gives BGR images we have to always convert it to RGB always remember this

In [4]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # do this on the very next line

In [5]:
print(img)

[[[153 179 186]
  [153 179 186]
  [149 176 185]
  ...
  [ 27  31  28]
  [ 26  27  25]
  [ 24  25  23]]

 [[149 175 182]
  [153 179 186]
  [151 178 187]
  ...
  [ 27  31  28]
  [ 26  27  27]
  [ 24  25  25]]

 [[155 181 188]
  [157 183 190]
  [155 183 189]
  ...
  [ 27  31  30]
  [ 26  27  27]
  [ 24  25  25]]

 ...

 [[ 17  17  19]
  [ 15  15  17]
  [ 13  13  15]
  ...
  [ 26  36  41]
  [ 26  34  40]
  [ 24  32  38]]

 [[ 15  16  16]
  [ 14  15  15]
  [ 12  13  13]
  ...
  [ 25  35  38]
  [ 27  35  39]
  [ 25  33  37]]

 [[ 14  15  15]
  [ 11  12  12]
  [ 11  12  12]
  ...
  [ 22  32  35]
  [ 23  31  35]
  [ 21  29  33]]]


Exercise: load img_000.png, print its shape and dtype. Then check: what is img.min() and img.max()?

In [6]:
ex_img = cv2.imread('/Users/asim/Downloads/Label_Practise/CamVid/train/0001TP_009240.png')

In [7]:
print(ex_img.shape)

(720, 960, 3)


In [8]:
print(ex_img.dtype)

uint8


In [9]:
ex_img.min()

np.uint8(0)

In [10]:
ex_img.max()

np.uint8(255)

## Pattern 3

### A Python class

In [11]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def bark(self):
        print(f"{self.name} says woof!")


# Use it

rex = Dog(name = 'Rex', age = 5)
rex.bark()
print(rex.age)

Rex says woof!
5


In [12]:
class SegDataset(Dataset):
    def __init__(self, img_dir):
        self.img_paths = sorted([...]) # store on the object

    def __len__(self):
        return len(self.img_path) # Just answer: how many samples?
    
    def __getitem__(self, idx):
        # Open file at index idx, return it
        path = self.img_paths[idx]



NameError: name 'Dataset' is not defined

Exercise: write a class Counter with an __init__ that sets self.count = 0, and a method add() that increases self.count by 1. Make one, call add() three times, print count. Send me your code.

In [ ]:
class Counter:
    def __init__(self, count, add):
        self.count = count
        self.add = add

    def add(self):
        self.count = 0 
        self.add = count+add

ad = Counter(count = 0, )